# Generated by Django 2.1.1 on 2018-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newslinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'newslinks',
                'managed': True,
            },
        ),
    ]
